language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

  licenses:
    - 'android-sdk-license-.+'

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
